language: python
python:
  - "2.7"
env:
# Make sure the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH}
before_install:
# Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python examples/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
install:
  - pip install -U -r examples/test_requirements.txt
  - python setup.py install
script:
  - ./runtests.sh
before_deploy:
  - ./mkdocs.sh
deploy:
  provider: pypi
  user: Josh.Johnston
  password:
    secure: GEUYOZo0QJWjxzrx0oxSvQOnEM/mXCdccj2WItcxc9xyFv2W80JSY+/b0ByFZxyAtz1pRmr9qd52NFRU5E1oS+1S01xXoQdr8o2ruWlMexa4rh25zuuc1M9VfQGraBsoqJHHku77wIqq+3ry4ADbGgtSecXemlKVDNIhfOanPPQ=
  on:
    tags: true
    repo: Trii/NoseGAE
