language: python
python:
  - "2.7"
install:
  - ./examples/install-gcloud-sdk.sh
  - pip install -r examples/test_requirements.txt
  - python setup.py install
script:
  - set -e
  - for i in $(ls ./examples/*/runtests.sh); do $i; done;
